#Jekyll configuration
title: Davidson College Library Github Page
email: digitallearning@davidson.edu
description: Sandbox environment intended for documentation and knowledge sharing, both internal and internal
url: "https://davidson-library.github.io"
markdown: kramdown
twitter_username: DavidsonLibrary
github_username:  Davidson-Library